// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

const moo = require('moo');
const {compile} = moo;

const lexer = compile({
    asignacion: ['<<<'],
    tipoVariable: ['entero', 'logico', 'decimalL', 'decimalC'],
    operadores: ['+', '-', '*', '/'],
    operadoresLogicos: ['menorQue', 'mayorQue', 'igualQue', 'menorIgualQue', 'mayorIgualQue', 'diferenteQue'],
    operadoresCortos: ["_mas mas", "_menos menos"],
    keyword: ['Para', 'mientrasQue', 'si', "sin't", 'caso', 'retornar', 'impresion#', 'salto'],
    WS:      /[ \t]{1,}/,
    comment: /\/\/.*?$/,
    number: /[0-9]+/,
    stringQuotes:  /"(?:\\["\\]|[^\n"\\])*"/,
    string:  /[a-zA-Z]+/,
    lparen:  '(',
    rparen:  ')',
    lbracket: '{',
    rbracket: '}',
    lcorch: '[',
    rcorch: ']',
    finLinea: '|',
    characterKey: ['#', ',' , '~', '.'],
    NL:      { match: /\n/, lineBreaks: true },
});
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "input$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$1", "symbols": []},
    {"name": "input$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$2", "symbols": []},
    {"name": "input$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$3", "symbols": []},
    {"name": "input$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$4", "symbols": []},
    {"name": "input$ebnf$1", "symbols": []},
    {"name": "input$ebnf$1", "symbols": ["input$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$2", "symbols": []},
    {"name": "input$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$2", "symbols": ["input$ebnf$2", "input$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$5", "symbols": []},
    {"name": "input$subexpression$6", "symbols": ["findelinea"]},
    {"name": "input$subexpression$6", "symbols": []},
    {"name": "input$ebnf$3", "symbols": []},
    {"name": "input$ebnf$3$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$3$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$3", "symbols": ["input$ebnf$3", "input$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": [{"literal":"~"}, "findelinea", {"literal":"entero"}, "input$subexpression$1", {"literal":"genesis"}, "input$subexpression$2", (lexer.has("lparen") ? {type: "lparen"} : lparen), "input$subexpression$3", (lexer.has("rparen") ? {type: "rparen"} : rparen), "input$subexpression$4", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "input$ebnf$1", "statements", "input$ebnf$2", {"literal":"apocalipsis"}, "input$subexpression$5", "input$subexpression$6", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "input$ebnf$3", "findelinea", {"literal":"~"}], "postprocess": (d) => eval('let textoEjecucion = document.getElementById("textoEjecucion"); '+d[12]+';')},
    {"name": "input$ebnf$4", "symbols": []},
    {"name": "input$ebnf$4", "symbols": ["input$ebnf$4", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$5", "symbols": []},
    {"name": "input$ebnf$5$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$5$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$5", "symbols": ["input$ebnf$5", "input$ebnf$5$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$7", "symbols": []},
    {"name": "input$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$8", "symbols": []},
    {"name": "input$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$9", "symbols": []},
    {"name": "input$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$10", "symbols": []},
    {"name": "input$ebnf$6", "symbols": []},
    {"name": "input$ebnf$6", "symbols": ["input$ebnf$6", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$7", "symbols": []},
    {"name": "input$ebnf$7$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$7$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$7", "symbols": ["input$ebnf$7", "input$ebnf$7$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$11", "symbols": []},
    {"name": "input$subexpression$12", "symbols": ["findelinea"]},
    {"name": "input$subexpression$12", "symbols": []},
    {"name": "input$ebnf$8", "symbols": []},
    {"name": "input$ebnf$8$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$8$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$8", "symbols": ["input$ebnf$8", "input$ebnf$8$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": [{"literal":"~"}, "findelinea", "input$ebnf$4", "statements", "input$ebnf$5", {"literal":"entero"}, "input$subexpression$7", {"literal":"genesis"}, "input$subexpression$8", (lexer.has("lparen") ? {type: "lparen"} : lparen), "input$subexpression$9", (lexer.has("rparen") ? {type: "rparen"} : rparen), "input$subexpression$10", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "input$ebnf$6", "statements", "input$ebnf$7", {"literal":"apocalipsis"}, "input$subexpression$11", "input$subexpression$12", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "input$ebnf$8", "findelinea", {"literal":"~"}], "postprocess": (d) => eval('let textoEjecucion = document.getElementById("textoEjecucion"); '+d[3]+'; '+d[15]+';')},
    {"name": "input$subexpression$13", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$13", "symbols": []},
    {"name": "input$subexpression$14", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$14", "symbols": []},
    {"name": "input$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$15", "symbols": []},
    {"name": "input$subexpression$16", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$16", "symbols": []},
    {"name": "input$ebnf$9", "symbols": []},
    {"name": "input$ebnf$9", "symbols": ["input$ebnf$9", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$10", "symbols": []},
    {"name": "input$ebnf$10$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$10$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$10", "symbols": ["input$ebnf$10", "input$ebnf$10$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$17", "symbols": []},
    {"name": "input$subexpression$18", "symbols": ["findelinea"]},
    {"name": "input$subexpression$18", "symbols": []},
    {"name": "input$subexpression$19", "symbols": ["espacioEnBlanco"]},
    {"name": "input$subexpression$19", "symbols": []},
    {"name": "input$subexpression$20", "symbols": ["findelinea"]},
    {"name": "input$subexpression$20", "symbols": []},
    {"name": "input$ebnf$11", "symbols": []},
    {"name": "input$ebnf$11", "symbols": ["input$ebnf$11", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$12", "symbols": []},
    {"name": "input$ebnf$12$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "input$ebnf$12$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "input$ebnf$12", "symbols": ["input$ebnf$12", "input$ebnf$12$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": [{"literal":"~"}, "findelinea", {"literal":"entero"}, "input$subexpression$13", {"literal":"genesis"}, "input$subexpression$14", (lexer.has("lparen") ? {type: "lparen"} : lparen), "input$subexpression$15", (lexer.has("rparen") ? {type: "rparen"} : rparen), "input$subexpression$16", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "input$ebnf$9", "statements", "input$ebnf$10", {"literal":"apocalipsis"}, "input$subexpression$17", "input$subexpression$18", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "input$subexpression$19", "input$subexpression$20", "input$ebnf$11", "statements", "input$ebnf$12", "findelinea", {"literal":"~"}], "postprocess": (d) => eval('let textoEjecucion = document.getElementById("textoEjecucion"); '+d[12]+'; '+d[21]+';')},
    {"name": "statement", "symbols": ["ifStatement"], "postprocess": (d) => d[0]},
    {"name": "statement", "symbols": ["whileStatement"], "postprocess": (d) => d[0]},
    {"name": "statement", "symbols": ["forStatement"], "postprocess": (d) => d[0]},
    {"name": "statement", "symbols": ["doWhileStatement"], "postprocess": (d) => d[0]},
    {"name": "statement", "symbols": ["funcionStatement"], "postprocess": (d) => d[0]},
    {"name": "statement", "symbols": ["returnStatement"], "postprocess": (d) => d[0]},
    {"name": "statement$subexpression$1", "symbols": ["findelinea"]},
    {"name": "statement$subexpression$1", "symbols": []},
    {"name": "statement", "symbols": ["callFuncionStatement", "statement$subexpression$1"], "postprocess": (d) => d[0]},
    {"name": "imp", "symbols": ["callFuncionStatement"], "postprocess": (d) => d[0]},
    {"name": "ifStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$1", "symbols": []},
    {"name": "ifStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$2", "symbols": []},
    {"name": "ifStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$3", "symbols": []},
    {"name": "ifStatement$ebnf$1", "symbols": []},
    {"name": "ifStatement$ebnf$1", "symbols": ["ifStatement$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$ebnf$2", "symbols": []},
    {"name": "ifStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "ifStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "ifStatement$ebnf$2", "symbols": ["ifStatement$ebnf$2", "ifStatement$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$4", "symbols": []},
    {"name": "ifStatement$subexpression$5", "symbols": ["findelinea"]},
    {"name": "ifStatement$subexpression$5", "symbols": []},
    {"name": "ifStatement", "symbols": [{"literal":"si"}, "ifStatement$subexpression$1", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "ifStatement$subexpression$2", {"literal":"entonces"}, "ifStatement$subexpression$3", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "ifStatement$ebnf$1", "statements", "ifStatement$ebnf$2", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "ifStatement$subexpression$4", "ifStatement$subexpression$5"], "postprocess": (d) => 'if('+d[3]+'){\n'+d[10]+'\n}'},
    {"name": "ifStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$6", "symbols": []},
    {"name": "ifStatement$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$7", "symbols": []},
    {"name": "ifStatement$ebnf$3", "symbols": []},
    {"name": "ifStatement$ebnf$3", "symbols": ["ifStatement$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$ebnf$4", "symbols": []},
    {"name": "ifStatement$ebnf$4$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "ifStatement$ebnf$4$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "ifStatement$ebnf$4", "symbols": ["ifStatement$ebnf$4", "ifStatement$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$8", "symbols": []},
    {"name": "ifStatement$subexpression$9", "symbols": ["findelinea"]},
    {"name": "ifStatement$subexpression$9", "symbols": []},
    {"name": "ifStatement", "symbols": ["ifStatement", "ifStatement$subexpression$6", {"literal":"sin't"}, "ifStatement$subexpression$7", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "ifStatement$ebnf$3", "statements", "ifStatement$ebnf$4", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "ifStatement$subexpression$8", "ifStatement$subexpression$9"], "postprocess": (d) => ''+d[0]+'else{\n'+d[6]+'\n}'},
    {"name": "ifStatement$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$10", "symbols": []},
    {"name": "ifStatement$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$11", "symbols": []},
    {"name": "ifStatement$subexpression$12", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$12", "symbols": []},
    {"name": "ifStatement$ebnf$5", "symbols": []},
    {"name": "ifStatement$ebnf$5", "symbols": ["ifStatement$ebnf$5", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$subexpression$13", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$13", "symbols": []},
    {"name": "ifStatement$subexpression$14", "symbols": ["findelinea"]},
    {"name": "ifStatement$subexpression$14", "symbols": []},
    {"name": "ifStatement", "symbols": [{"literal":"si"}, "ifStatement$subexpression$10", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "ifStatement$subexpression$11", {"literal":"entonces"}, "ifStatement$subexpression$12", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "ifStatement$ebnf$5", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "ifStatement$subexpression$13", "ifStatement$subexpression$14"], "postprocess": (d) => 'if('+d[3]+'){}'},
    {"name": "ifStatement$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$15", "symbols": []},
    {"name": "ifStatement$subexpression$16", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$16", "symbols": []},
    {"name": "ifStatement$ebnf$6", "symbols": []},
    {"name": "ifStatement$ebnf$6", "symbols": ["ifStatement$ebnf$6", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ifStatement$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "ifStatement$subexpression$17", "symbols": []},
    {"name": "ifStatement$subexpression$18", "symbols": ["findelinea"]},
    {"name": "ifStatement$subexpression$18", "symbols": []},
    {"name": "ifStatement", "symbols": ["ifStatement", "ifStatement$subexpression$15", {"literal":"sin't"}, "ifStatement$subexpression$16", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "ifStatement$ebnf$6", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "ifStatement$subexpression$17", "ifStatement$subexpression$18"], "postprocess": (d) => ''+d[0]+'else{}'},
    {"name": "whileStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$1", "symbols": []},
    {"name": "whileStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$2", "symbols": []},
    {"name": "whileStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$3", "symbols": []},
    {"name": "whileStatement$ebnf$1", "symbols": []},
    {"name": "whileStatement$ebnf$1", "symbols": ["whileStatement$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "whileStatement$ebnf$2", "symbols": []},
    {"name": "whileStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "whileStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "whileStatement$ebnf$2", "symbols": ["whileStatement$ebnf$2", "whileStatement$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "whileStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$4", "symbols": []},
    {"name": "whileStatement$subexpression$5", "symbols": ["findelinea"]},
    {"name": "whileStatement$subexpression$5", "symbols": []},
    {"name": "whileStatement", "symbols": [{"literal":"mientrasQue"}, "whileStatement$subexpression$1", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "whileStatement$subexpression$2", {"literal":"entonces"}, "whileStatement$subexpression$3", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "whileStatement$ebnf$1", "statements", "whileStatement$ebnf$2", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "whileStatement$subexpression$4", "whileStatement$subexpression$5"], "postprocess": (d) => 'while('+d[3]+'){\n'+d[10]+'\n}'},
    {"name": "whileStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$6", "symbols": []},
    {"name": "whileStatement$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$7", "symbols": []},
    {"name": "whileStatement$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$8", "symbols": []},
    {"name": "whileStatement$ebnf$3", "symbols": []},
    {"name": "whileStatement$ebnf$3", "symbols": ["whileStatement$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "whileStatement$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "whileStatement$subexpression$9", "symbols": []},
    {"name": "whileStatement$subexpression$10", "symbols": ["findelinea"]},
    {"name": "whileStatement$subexpression$10", "symbols": []},
    {"name": "whileStatement", "symbols": [{"literal":"mientrasQue"}, "whileStatement$subexpression$6", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "whileStatement$subexpression$7", {"literal":"entonces"}, "whileStatement$subexpression$8", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "whileStatement$ebnf$3", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "whileStatement$subexpression$9", "whileStatement$subexpression$10"], "postprocess": (d) => 'while('+d[3]+'){}'},
    {"name": "doWhileStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$1", "symbols": []},
    {"name": "doWhileStatement$ebnf$1", "symbols": []},
    {"name": "doWhileStatement$ebnf$1", "symbols": ["doWhileStatement$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "doWhileStatement$ebnf$2", "symbols": []},
    {"name": "doWhileStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "doWhileStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "doWhileStatement$ebnf$2", "symbols": ["doWhileStatement$ebnf$2", "doWhileStatement$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "doWhileStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$2", "symbols": []},
    {"name": "doWhileStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$3", "symbols": []},
    {"name": "doWhileStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$4", "symbols": []},
    {"name": "doWhileStatement$subexpression$5", "symbols": ["findelinea"]},
    {"name": "doWhileStatement$subexpression$5", "symbols": []},
    {"name": "doWhileStatement", "symbols": [{"literal":"hacer"}, "doWhileStatement$subexpression$1", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "doWhileStatement$ebnf$1", "statements", "doWhileStatement$ebnf$2", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "doWhileStatement$subexpression$2", {"literal":"mientrasQue"}, "doWhileStatement$subexpression$3", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "doWhileStatement$subexpression$4", "doWhileStatement$subexpression$5"], "postprocess": (d) => 'do{\n'+d[4]+'\n}while('+d[11]+')'},
    {"name": "doWhileStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$6", "symbols": []},
    {"name": "doWhileStatement$ebnf$3", "symbols": []},
    {"name": "doWhileStatement$ebnf$3", "symbols": ["doWhileStatement$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "doWhileStatement$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$7", "symbols": []},
    {"name": "doWhileStatement$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$8", "symbols": []},
    {"name": "doWhileStatement$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "doWhileStatement$subexpression$9", "symbols": []},
    {"name": "doWhileStatement$subexpression$10", "symbols": ["findelinea"]},
    {"name": "doWhileStatement$subexpression$10", "symbols": []},
    {"name": "doWhileStatement", "symbols": [{"literal":"hacer"}, "doWhileStatement$subexpression$6", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "doWhileStatement$ebnf$3", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "doWhileStatement$subexpression$7", {"literal":"mientrasQue"}, "doWhileStatement$subexpression$8", (lexer.has("lparen") ? {type: "lparen"} : lparen), "operacionlogica", (lexer.has("rparen") ? {type: "rparen"} : rparen), "doWhileStatement$subexpression$9", "doWhileStatement$subexpression$10"], "postprocess": (d) => 'do{}while('+d[11]+')'},
    {"name": "forStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$1", "symbols": []},
    {"name": "forStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$2", "symbols": []},
    {"name": "forStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$3", "symbols": []},
    {"name": "forStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$4", "symbols": []},
    {"name": "forStatement$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$5", "symbols": []},
    {"name": "forStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$6", "symbols": []},
    {"name": "forStatement$subexpression$7", "symbols": ["operacion"]},
    {"name": "forStatement$subexpression$7", "symbols": ["operacionCorta"]},
    {"name": "forStatement$subexpression$7", "symbols": ["operacionlogica"]},
    {"name": "forStatement$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$8", "symbols": []},
    {"name": "forStatement$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$9", "symbols": []},
    {"name": "forStatement$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$10", "symbols": []},
    {"name": "forStatement$ebnf$1", "symbols": []},
    {"name": "forStatement$ebnf$1", "symbols": ["forStatement$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "forStatement$ebnf$2", "symbols": []},
    {"name": "forStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "forStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "forStatement$ebnf$2", "symbols": ["forStatement$ebnf$2", "forStatement$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "forStatement$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$11", "symbols": []},
    {"name": "forStatement$subexpression$12", "symbols": ["findelinea"]},
    {"name": "forStatement$subexpression$12", "symbols": []},
    {"name": "forStatement", "symbols": [{"literal":"Para"}, "forStatement$subexpression$1", (lexer.has("lparen") ? {type: "lparen"} : lparen), "forStatement$subexpression$2", "declaracion", "forStatement$subexpression$3", {"literal":"|"}, "forStatement$subexpression$4", "operacionlogica", "forStatement$subexpression$5", {"literal":"|"}, "forStatement$subexpression$6", "forStatement$subexpression$7", "forStatement$subexpression$8", (lexer.has("rparen") ? {type: "rparen"} : rparen), "forStatement$subexpression$9", {"literal":"entonces"}, "forStatement$subexpression$10", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "forStatement$ebnf$1", "statements", "forStatement$ebnf$2", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "forStatement$subexpression$11", "forStatement$subexpression$12"], "postprocess": (d) => 'for('+d[4]+';'+d[8]+';'+d[12]+'){\n'+d[20]+'\n}'},
    {"name": "forStatement$subexpression$13", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$13", "symbols": []},
    {"name": "forStatement$subexpression$14", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$14", "symbols": []},
    {"name": "forStatement$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$15", "symbols": []},
    {"name": "forStatement$subexpression$16", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$16", "symbols": []},
    {"name": "forStatement$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$17", "symbols": []},
    {"name": "forStatement$subexpression$18", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$18", "symbols": []},
    {"name": "forStatement$subexpression$19", "symbols": ["operacion"]},
    {"name": "forStatement$subexpression$19", "symbols": ["operacionCorta"]},
    {"name": "forStatement$subexpression$19", "symbols": ["operacionlogica"]},
    {"name": "forStatement$subexpression$20", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$20", "symbols": []},
    {"name": "forStatement$subexpression$21", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$21", "symbols": []},
    {"name": "forStatement$subexpression$22", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$22", "symbols": []},
    {"name": "forStatement$ebnf$3", "symbols": []},
    {"name": "forStatement$ebnf$3", "symbols": ["forStatement$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "forStatement$subexpression$23", "symbols": ["espacioEnBlanco"]},
    {"name": "forStatement$subexpression$23", "symbols": []},
    {"name": "forStatement$subexpression$24", "symbols": ["findelinea"]},
    {"name": "forStatement$subexpression$24", "symbols": []},
    {"name": "forStatement", "symbols": [{"literal":"Para"}, "forStatement$subexpression$13", (lexer.has("lparen") ? {type: "lparen"} : lparen), "forStatement$subexpression$14", "declaracion", "forStatement$subexpression$15", {"literal":"|"}, "forStatement$subexpression$16", "operacionlogica", "forStatement$subexpression$17", {"literal":"|"}, "forStatement$subexpression$18", "forStatement$subexpression$19", "forStatement$subexpression$20", (lexer.has("rparen") ? {type: "rparen"} : rparen), "forStatement$subexpression$21", {"literal":"entonces"}, "forStatement$subexpression$22", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "forStatement$ebnf$3", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "forStatement$subexpression$23", "forStatement$subexpression$24"], "postprocess": (d) => 'for('+d[4]+';'+d[8]+';'+d[12]+'){}'},
    {"name": "callFuncionStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$1", "symbols": []},
    {"name": "callFuncionStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$2", "symbols": []},
    {"name": "callFuncionStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$3", "symbols": []},
    {"name": "callFuncionStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$4", "symbols": []},
    {"name": "callFuncionStatement", "symbols": [(lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "callFuncionStatement$subexpression$1", "argumentos", "callFuncionStatement$subexpression$2", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "callFuncionStatement$subexpression$3", (lexer.has("string") ? {type: "string"} : string), "callFuncionStatement$subexpression$4"], "postprocess": (d) => ''+d[6]+'('+d[2]+')'},
    {"name": "callFuncionStatement$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$5", "symbols": []},
    {"name": "callFuncionStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$6", "symbols": []},
    {"name": "callFuncionStatement$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "callFuncionStatement$subexpression$7", "symbols": []},
    {"name": "callFuncionStatement", "symbols": [(lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "callFuncionStatement$subexpression$5", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "callFuncionStatement$subexpression$6", (lexer.has("string") ? {type: "string"} : string), "callFuncionStatement$subexpression$7"], "postprocess": (d) => ''+d[4]+'()'},
    {"name": "funcionStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$1", "symbols": []},
    {"name": "funcionStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$2", "symbols": []},
    {"name": "funcionStatement$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$3", "symbols": []},
    {"name": "funcionStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$4", "symbols": []},
    {"name": "funcionStatement$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$5", "symbols": []},
    {"name": "funcionStatement$ebnf$1", "symbols": []},
    {"name": "funcionStatement$ebnf$1", "symbols": ["funcionStatement$ebnf$1", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$ebnf$2", "symbols": []},
    {"name": "funcionStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "funcionStatement$ebnf$2$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "funcionStatement$ebnf$2", "symbols": ["funcionStatement$ebnf$2", "funcionStatement$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$6", "symbols": []},
    {"name": "funcionStatement$subexpression$7", "symbols": ["findelinea"]},
    {"name": "funcionStatement$subexpression$7", "symbols": []},
    {"name": "funcionStatement", "symbols": [(lexer.has("tipoVariable") ? {type: "tipoVariable"} : tipoVariable), "funcionStatement$subexpression$1", (lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "funcionStatement$subexpression$2", "argumentos", "funcionStatement$subexpression$3", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "funcionStatement$subexpression$4", (lexer.has("string") ? {type: "string"} : string), "funcionStatement$subexpression$5", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "funcionStatement$ebnf$1", "statements", "funcionStatement$ebnf$2", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "funcionStatement$subexpression$6", "funcionStatement$subexpression$7"], "postprocess": (d) => 'function '+d[8]+'('+d[4]+'){\n'+d[12]+'\n}'},
    {"name": "funcionStatement$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$8", "symbols": []},
    {"name": "funcionStatement$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$9", "symbols": []},
    {"name": "funcionStatement$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$10", "symbols": []},
    {"name": "funcionStatement$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$11", "symbols": []},
    {"name": "funcionStatement$subexpression$12", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$12", "symbols": []},
    {"name": "funcionStatement$ebnf$3", "symbols": []},
    {"name": "funcionStatement$ebnf$3", "symbols": ["funcionStatement$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$subexpression$13", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$13", "symbols": []},
    {"name": "funcionStatement$subexpression$14", "symbols": ["findelinea"]},
    {"name": "funcionStatement$subexpression$14", "symbols": []},
    {"name": "funcionStatement", "symbols": [(lexer.has("tipoVariable") ? {type: "tipoVariable"} : tipoVariable), "funcionStatement$subexpression$8", (lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "funcionStatement$subexpression$9", "argumentos", "funcionStatement$subexpression$10", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "funcionStatement$subexpression$11", (lexer.has("string") ? {type: "string"} : string), "funcionStatement$subexpression$12", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "funcionStatement$ebnf$3", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "funcionStatement$subexpression$13", "funcionStatement$subexpression$14"], "postprocess": (d) => 'function '+d[8]+'('+d[4]+'){}'},
    {"name": "funcionStatement$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$15", "symbols": []},
    {"name": "funcionStatement$subexpression$16", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$16", "symbols": []},
    {"name": "funcionStatement$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$17", "symbols": []},
    {"name": "funcionStatement$subexpression$18", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$18", "symbols": []},
    {"name": "funcionStatement$ebnf$4", "symbols": []},
    {"name": "funcionStatement$ebnf$4", "symbols": ["funcionStatement$ebnf$4", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$ebnf$5", "symbols": []},
    {"name": "funcionStatement$ebnf$5$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "funcionStatement$ebnf$5$subexpression$1", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)]},
    {"name": "funcionStatement$ebnf$5", "symbols": ["funcionStatement$ebnf$5", "funcionStatement$ebnf$5$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$subexpression$19", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$19", "symbols": []},
    {"name": "funcionStatement$subexpression$20", "symbols": ["findelinea"]},
    {"name": "funcionStatement$subexpression$20", "symbols": []},
    {"name": "funcionStatement", "symbols": [(lexer.has("tipoVariable") ? {type: "tipoVariable"} : tipoVariable), "funcionStatement$subexpression$15", (lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "funcionStatement$subexpression$16", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "funcionStatement$subexpression$17", (lexer.has("string") ? {type: "string"} : string), "funcionStatement$subexpression$18", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "funcionStatement$ebnf$4", "statements", "funcionStatement$ebnf$5", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "funcionStatement$subexpression$19", "funcionStatement$subexpression$20"], "postprocess": (d) => 'function '+d[6]+'(){\n'+d[10]+'\n}'},
    {"name": "funcionStatement$subexpression$21", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$21", "symbols": []},
    {"name": "funcionStatement$subexpression$22", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$22", "symbols": []},
    {"name": "funcionStatement$subexpression$23", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$23", "symbols": []},
    {"name": "funcionStatement$subexpression$24", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$24", "symbols": []},
    {"name": "funcionStatement$ebnf$6", "symbols": []},
    {"name": "funcionStatement$ebnf$6", "symbols": ["funcionStatement$ebnf$6", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "funcionStatement$subexpression$25", "symbols": ["espacioEnBlanco"]},
    {"name": "funcionStatement$subexpression$25", "symbols": []},
    {"name": "funcionStatement$subexpression$26", "symbols": ["findelinea"]},
    {"name": "funcionStatement$subexpression$26", "symbols": []},
    {"name": "funcionStatement", "symbols": [(lexer.has("tipoVariable") ? {type: "tipoVariable"} : tipoVariable), "funcionStatement$subexpression$21", (lexer.has("lcorch") ? {type: "lcorch"} : lcorch), "funcionStatement$subexpression$22", (lexer.has("rcorch") ? {type: "rcorch"} : rcorch), "funcionStatement$subexpression$23", (lexer.has("string") ? {type: "string"} : string), "funcionStatement$subexpression$24", (lexer.has("lbracket") ? {type: "lbracket"} : lbracket), "funcionStatement$ebnf$6", (lexer.has("rbracket") ? {type: "rbracket"} : rbracket), "funcionStatement$subexpression$25", "funcionStatement$subexpression$26"], "postprocess": (d) => 'function '+d[6]+'(){}'},
    {"name": "returnStatement$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "returnStatement$subexpression$1", "symbols": []},
    {"name": "returnStatement$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "returnStatement$subexpression$2", "symbols": []},
    {"name": "returnStatement$subexpression$3", "symbols": ["findelinea"]},
    {"name": "returnStatement$subexpression$3", "symbols": []},
    {"name": "returnStatement", "symbols": [{"literal":"retornar"}, "returnStatement$subexpression$1", "value", "returnStatement$subexpression$2", "returnStatement$subexpression$3"], "postprocess": (d) => 'return '+d[2]+''},
    {"name": "returnStatement$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "returnStatement$subexpression$4", "symbols": []},
    {"name": "returnStatement$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "returnStatement$subexpression$5", "symbols": []},
    {"name": "returnStatement$subexpression$6", "symbols": ["findelinea"]},
    {"name": "returnStatement$subexpression$6", "symbols": []},
    {"name": "returnStatement", "symbols": [{"literal":"retornar"}, "returnStatement$subexpression$4", "variable", "returnStatement$subexpression$5", "returnStatement$subexpression$6"], "postprocess": (d) => 'return '+d[2]+''},
    {"name": "argumentos$subexpression$1", "symbols": ["variable"]},
    {"name": "argumentos$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "argumentos", "symbols": ["argumentos$subexpression$1"]},
    {"name": "argumentos$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "argumentos$subexpression$2", "symbols": []},
    {"name": "argumentos$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "argumentos$subexpression$3", "symbols": []},
    {"name": "argumentos$subexpression$4", "symbols": ["variable"]},
    {"name": "argumentos$subexpression$4", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "argumentos", "symbols": ["argumentos", "argumentos$subexpression$2", {"literal":","}, "argumentos$subexpression$3", "argumentos$subexpression$4"], "postprocess": (d) => ''+d[0]+','+d[4]+''},
    {"name": "statements", "symbols": ["statement"]},
    {"name": "statements$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "statements$subexpression$1", "symbols": []},
    {"name": "statements", "symbols": ["statements", "statements$subexpression$1", "statement"], "postprocess": (d) => d[0]+';\n'+d[2]},
    {"name": "statement", "symbols": ["operacion"]},
    {"name": "statement", "symbols": ["impStatement"]},
    {"name": "statement", "symbols": ["declaracion"]},
    {"name": "statement", "symbols": ["asignacion"]},
    {"name": "statement", "symbols": ["operacionCorta"]},
    {"name": "statement", "symbols": ["espacioEnBlanco", "statement"], "postprocess": (d) => d[1]},
    {"name": "impStatement$subexpression$1", "symbols": ["findelinea"]},
    {"name": "impStatement$subexpression$1", "symbols": []},
    {"name": "impStatement", "symbols": [{"literal":"impresion#"}, "imp", "impStatement$subexpression$1"], "postprocess": (d) => 'textoEjecucion.innerHTML = textoEjecucion.innerHTML+'+d[1]+''},
    {"name": "imp", "symbols": ["variable"], "postprocess": (d) => d[0]},
    {"name": "imp$subexpression$1", "symbols": ["operacion"]},
    {"name": "imp$subexpression$1", "symbols": ["operacionCorta"]},
    {"name": "imp$subexpression$1", "symbols": ["operacionlogica"]},
    {"name": "imp", "symbols": ["imp$subexpression$1"], "postprocess": (d) => '('+d[0]+')'},
    {"name": "imp", "symbols": [(lexer.has("stringQuotes") ? {type: "stringQuotes"} : stringQuotes)], "postprocess": (d) => d[0]},
    {"name": "imp", "symbols": ["imp", {"literal":"#"}, "imp"], "postprocess": (d) => d[0]+'+'+d[2]},
    {"name": "asignacion$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "asignacion$subexpression$1", "symbols": []},
    {"name": "asignacion$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "asignacion$subexpression$2", "symbols": []},
    {"name": "asignacion", "symbols": [(lexer.has("string") ? {type: "string"} : string), "asignacion$subexpression$1", {"literal":"<<<"}, "asignacion$subexpression$2", "value", "findelinea"], "postprocess": (d) => ''+d[0]+' = '+d[4]+''},
    {"name": "value", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "value", "symbols": [(lexer.has("stringQuotes") ? {type: "stringQuotes"} : stringQuotes)]},
    {"name": "value", "symbols": [{"literal":"true"}]},
    {"name": "value", "symbols": [{"literal":"false"}]},
    {"name": "value", "symbols": ["operacion"]},
    {"name": "value", "symbols": ["operacionCorta"]},
    {"name": "value", "symbols": ["operacionlogica"]},
    {"name": "operacion$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$2", "symbols": []},
    {"name": "operacion$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$3", "symbols": []},
    {"name": "operacion$subexpression$4$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$4$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$4", "symbols": ["operacion$subexpression$4$subexpression$1"]},
    {"name": "operacion$subexpression$4", "symbols": ["operacion"]},
    {"name": "operacion", "symbols": ["operacion$subexpression$1", "operacion$subexpression$2", {"literal":"+"}, "operacion$subexpression$3", "operacion$subexpression$4", "findelinea"], "postprocess": (d) => ''+d[0]+'+'+d[4]+''},
    {"name": "operacion$subexpression$5", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$5", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$6", "symbols": []},
    {"name": "operacion$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$7", "symbols": []},
    {"name": "operacion$subexpression$8$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$8$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$8", "symbols": ["operacion$subexpression$8$subexpression$1"]},
    {"name": "operacion$subexpression$8", "symbols": ["operacion"]},
    {"name": "operacion", "symbols": ["operacion$subexpression$5", "operacion$subexpression$6", {"literal":"-"}, "operacion$subexpression$7", "operacion$subexpression$8", "findelinea"], "postprocess": (d) => ''+d[0]+'-'+d[4]+''},
    {"name": "operacion$subexpression$9", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$9", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$10", "symbols": []},
    {"name": "operacion$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$11", "symbols": []},
    {"name": "operacion$subexpression$12$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$12$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$12", "symbols": ["operacion$subexpression$12$subexpression$1"]},
    {"name": "operacion$subexpression$12", "symbols": ["operacion"]},
    {"name": "operacion", "symbols": ["operacion$subexpression$9", "operacion$subexpression$10", {"literal":"*"}, "operacion$subexpression$11", "operacion$subexpression$12", "findelinea"], "postprocess": (d) => ''+d[0]+'*'+d[4]+''},
    {"name": "operacion$subexpression$13", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$13", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$14", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$14", "symbols": []},
    {"name": "operacion$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "operacion$subexpression$15", "symbols": []},
    {"name": "operacion$subexpression$16$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacion$subexpression$16$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacion$subexpression$16", "symbols": ["operacion$subexpression$16$subexpression$1"]},
    {"name": "operacion$subexpression$16", "symbols": ["operacion"]},
    {"name": "operacion", "symbols": ["operacion$subexpression$13", "operacion$subexpression$14", {"literal":"/"}, "operacion$subexpression$15", "operacion$subexpression$16", "findelinea"], "postprocess": (d) => ''+d[0]+'/'+d[4]+''},
    {"name": "operacionlogica$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$2", "symbols": []},
    {"name": "operacionlogica$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$3", "symbols": []},
    {"name": "operacionlogica$subexpression$4$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$4$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$4$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$4", "symbols": ["operacionlogica$subexpression$4$subexpression$1"]},
    {"name": "operacionlogica$subexpression$4", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$5", "symbols": []},
    {"name": "operacionlogica$subexpression$6", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$6", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$1", "operacionlogica$subexpression$2", {"literal":"mayorQue"}, "operacionlogica$subexpression$3", "operacionlogica$subexpression$4", "operacionlogica$subexpression$5", "operacionlogica$subexpression$6"], "postprocess": (d) => ''+d[0]+'>'+d[4]+''},
    {"name": "operacionlogica$subexpression$7", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$7", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$7", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$8", "symbols": []},
    {"name": "operacionlogica$subexpression$9", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$9", "symbols": []},
    {"name": "operacionlogica$subexpression$10$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$10$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$10$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$10", "symbols": ["operacionlogica$subexpression$10$subexpression$1"]},
    {"name": "operacionlogica$subexpression$10", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$11", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$11", "symbols": []},
    {"name": "operacionlogica$subexpression$12", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$12", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$7", "operacionlogica$subexpression$8", {"literal":"menorQue"}, "operacionlogica$subexpression$9", "operacionlogica$subexpression$10", "operacionlogica$subexpression$11", "operacionlogica$subexpression$12"], "postprocess": (d) => ''+d[0]+'<'+d[4]+''},
    {"name": "operacionlogica$subexpression$13", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$13", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$13", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$14", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$14", "symbols": []},
    {"name": "operacionlogica$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$15", "symbols": []},
    {"name": "operacionlogica$subexpression$16$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$16$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$16$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$16", "symbols": ["operacionlogica$subexpression$16$subexpression$1"]},
    {"name": "operacionlogica$subexpression$16", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$17", "symbols": []},
    {"name": "operacionlogica$subexpression$18", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$18", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$13", "operacionlogica$subexpression$14", {"literal":"mayorIgualQue"}, "operacionlogica$subexpression$15", "operacionlogica$subexpression$16", "operacionlogica$subexpression$17", "operacionlogica$subexpression$18"], "postprocess": (d) => ''+d[0]+'>='+d[4]+''},
    {"name": "operacionlogica$subexpression$19", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$19", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$19", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$20", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$20", "symbols": []},
    {"name": "operacionlogica$subexpression$21", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$21", "symbols": []},
    {"name": "operacionlogica$subexpression$22$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$22$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$22$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$22", "symbols": ["operacionlogica$subexpression$22$subexpression$1"]},
    {"name": "operacionlogica$subexpression$22", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$23", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$23", "symbols": []},
    {"name": "operacionlogica$subexpression$24", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$24", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$19", "operacionlogica$subexpression$20", {"literal":"menorIgualQue"}, "operacionlogica$subexpression$21", "operacionlogica$subexpression$22", "operacionlogica$subexpression$23", "operacionlogica$subexpression$24"], "postprocess": (d) => ''+d[0]+'<='+d[4]+''},
    {"name": "operacionlogica$subexpression$25", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$25", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$25", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$26", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$26", "symbols": []},
    {"name": "operacionlogica$subexpression$27", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$27", "symbols": []},
    {"name": "operacionlogica$subexpression$28$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$28$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$28$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$28", "symbols": ["operacionlogica$subexpression$28$subexpression$1"]},
    {"name": "operacionlogica$subexpression$28", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$29", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$29", "symbols": []},
    {"name": "operacionlogica$subexpression$30", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$30", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$25", "operacionlogica$subexpression$26", {"literal":"igualQue"}, "operacionlogica$subexpression$27", "operacionlogica$subexpression$28", "operacionlogica$subexpression$29", "operacionlogica$subexpression$30"], "postprocess": (d) => ''+d[0]+'=='+d[4]+''},
    {"name": "operacionlogica$subexpression$31", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$31", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$31", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$32", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$32", "symbols": []},
    {"name": "operacionlogica$subexpression$33", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$33", "symbols": []},
    {"name": "operacionlogica$subexpression$34$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionlogica$subexpression$34$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionlogica$subexpression$34$subexpression$1", "symbols": ["numberDecimal"]},
    {"name": "operacionlogica$subexpression$34", "symbols": ["operacionlogica$subexpression$34$subexpression$1"]},
    {"name": "operacionlogica$subexpression$34", "symbols": ["operacionlogica"]},
    {"name": "operacionlogica$subexpression$35", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionlogica$subexpression$35", "symbols": []},
    {"name": "operacionlogica$subexpression$36", "symbols": ["findelinea"]},
    {"name": "operacionlogica$subexpression$36", "symbols": []},
    {"name": "operacionlogica", "symbols": ["operacionlogica$subexpression$31", "operacionlogica$subexpression$32", {"literal":"diferenteQue"}, "operacionlogica$subexpression$33", "operacionlogica$subexpression$34", "operacionlogica$subexpression$35", "operacionlogica$subexpression$36"], "postprocess": (d) => ''+d[0]+'!='+d[4]+''},
    {"name": "operacionCorta$subexpression$1", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionCorta$subexpression$1", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionCorta$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionCorta$subexpression$2", "symbols": []},
    {"name": "operacionCorta$subexpression$3", "symbols": ["findelinea"]},
    {"name": "operacionCorta$subexpression$3", "symbols": []},
    {"name": "operacionCorta", "symbols": ["operacionCorta$subexpression$1", {"literal":"_mas mas"}, "operacionCorta$subexpression$2", "operacionCorta$subexpression$3"], "postprocess": (d) => ''+d[0]+'+=1'},
    {"name": "operacionCorta$subexpression$4", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "operacionCorta$subexpression$4", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "operacionCorta$subexpression$5", "symbols": ["espacioEnBlanco"]},
    {"name": "operacionCorta$subexpression$5", "symbols": []},
    {"name": "operacionCorta$subexpression$6", "symbols": ["findelinea"]},
    {"name": "operacionCorta$subexpression$6", "symbols": []},
    {"name": "operacionCorta", "symbols": ["operacionCorta$subexpression$4", {"literal":"_menos menos"}, "operacionCorta$subexpression$5", "operacionCorta$subexpression$6"], "postprocess": (d) => ''+d[0]+'-=1'},
    {"name": "declaracion$subexpression$1", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$1", "symbols": []},
    {"name": "declaracion$subexpression$2", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$2", "symbols": []},
    {"name": "declaracion$subexpression$3", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$3", "symbols": []},
    {"name": "declaracion$subexpression$4", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$4", "symbols": []},
    {"name": "declaracion$subexpression$5", "symbols": ["findelinea"]},
    {"name": "declaracion$subexpression$5", "symbols": []},
    {"name": "declaracion", "symbols": [{"literal":"entero"}, "declaracion$subexpression$1", "variable", "declaracion$subexpression$2", {"literal":"<<<"}, "declaracion$subexpression$3", (lexer.has("number") ? {type: "number"} : number), "declaracion$subexpression$4", "declaracion$subexpression$5"], "postprocess": (d) => 'let '+d[2]+' = '+d[6]+''},
    {"name": "declaracion$subexpression$6", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$6", "symbols": []},
    {"name": "declaracion$subexpression$7", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$7", "symbols": []},
    {"name": "declaracion$subexpression$8", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$8", "symbols": []},
    {"name": "declaracion$subexpression$9", "symbols": [{"literal":"true"}]},
    {"name": "declaracion$subexpression$9", "symbols": [{"literal":"false"}]},
    {"name": "declaracion$subexpression$10", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$10", "symbols": []},
    {"name": "declaracion$subexpression$11", "symbols": ["findelinea"]},
    {"name": "declaracion$subexpression$11", "symbols": []},
    {"name": "declaracion", "symbols": [{"literal":"logico"}, "declaracion$subexpression$6", "variable", "declaracion$subexpression$7", {"literal":"<<<"}, "declaracion$subexpression$8", "declaracion$subexpression$9", "declaracion$subexpression$10", "declaracion$subexpression$11"], "postprocess": (d) => 'let '+d[2]+' = '+d[6]+''},
    {"name": "declaracion$subexpression$12", "symbols": [{"literal":"decimalC"}]},
    {"name": "declaracion$subexpression$12", "symbols": [{"literal":"decimalL"}]},
    {"name": "declaracion$subexpression$13", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$13", "symbols": []},
    {"name": "declaracion$subexpression$14", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$14", "symbols": []},
    {"name": "declaracion$subexpression$15", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$15", "symbols": []},
    {"name": "declaracion$subexpression$16", "symbols": ["numberDecimal"]},
    {"name": "declaracion$subexpression$16", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "declaracion$subexpression$17", "symbols": ["espacioEnBlanco"]},
    {"name": "declaracion$subexpression$17", "symbols": []},
    {"name": "declaracion$subexpression$18", "symbols": ["findelinea"]},
    {"name": "declaracion$subexpression$18", "symbols": []},
    {"name": "declaracion", "symbols": ["declaracion$subexpression$12", "declaracion$subexpression$13", "variable", "declaracion$subexpression$14", {"literal":"<<<"}, "declaracion$subexpression$15", "declaracion$subexpression$16", "declaracion$subexpression$17", "declaracion$subexpression$18"], "postprocess": (d) => 'let '+d[2]+' = '+d[6]+''},
    {"name": "variable$ebnf$1", "symbols": []},
    {"name": "variable$ebnf$1", "symbols": ["variable$ebnf$1", (lexer.has("number") ? {type: "number"} : number)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "variable", "symbols": [(lexer.has("string") ? {type: "string"} : string), "variable$ebnf$1"], "postprocess": (d) => ''+d[0]+d[1]+''},
    {"name": "numberDecimal", "symbols": [(lexer.has("number") ? {type: "number"} : number), {"literal":"."}, (lexer.has("number") ? {type: "number"} : number)], "postprocess": (d) => d[0]+'.'+d[2]},
    {"name": "findelinea", "symbols": ["espacioEnBlanco"]},
    {"name": "findelinea", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "findelinea", "symbols": [(lexer.has("finLinea") ? {type: "finLinea"} : finLinea), "findelinea"], "postprocess": (d) => ';'},
    {"name": "espacioEnBlanco", "symbols": [(lexer.has("WS") ? {type: "WS"} : WS)], "postprocess": (d) => ' '}
]
  , ParserStart: "input"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
